export default {
  INIT_FILTER: 'INIT_FILTER',
  APPLY_FILTER: 'APPLY_FILTER',
  UPDATE_FILTER_REGION: 'UPDATE_FILTER_REGION',
  UPDATE_FILTER_ORDER: 'UPDATE_FILTER_ORDER',

  FLOW_REINIT: 'FLOW_REINIT',
  FLOW_NEED_ACCEPTANCE: 'FLOW_NEED_ACCEPTANCE',
  FLOW_NEED_CONNECTION: 'FLOW_NEED_CONNECTION',
  FLOW_ALL_GOOD: 'FLOW_ALL_GOOD',
};
